defaults:
  - _self_
  - user_settings: user_settings
  - hydra: base
  - llm: local

project_path: ${user_settings.project_path}
result_dir: ${user_settings.result_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}

